version: '3.8'

services:
  # PostgreSQL Database for User Service
  user-db:
    image: postgres:15
    environment:
      POSTGRES_DB: user_service
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data

  # PostgreSQL Database for Product Service
  product-db:
    image: postgres:15
    environment:
      POSTGRES_DB: product_service
      POSTGRES_USER: product_admin
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - product_db_data:/var/lib/postgresql/data

  # PostgreSQL Database for Order Service
  order-db:
    image: postgres:15
    environment:
      POSTGRES_DB: order_service
      POSTGRES_USER: order_admin
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - order_db_data:/var/lib/postgresql/data

  # User Service
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8001:80"
    depends_on:
      - user-db
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: user-db
      DB_PORT: 5432
      DB_DATABASE: user_service
      DB_USERNAME: user_admin
      DB_PASSWORD: password

  # Product Service
  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - "8002:80"
    depends_on:
      - product-db
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: product-db
      DB_PORT: 5432
      DB_DATABASE: product_service
      DB_USERNAME: product_admin
      DB_PASSWORD: password

  # Order Service
  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - "8003:80"
    depends_on:
      - order-db
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: order-db
      DB_PORT: 5432
      DB_DATABASE: order_service
      DB_USERNAME: order_admin
      DB_PASSWORD: password

volumes:
  user_db_data:
  product_db_data:
  order_db_data:
